### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [hypirion/c-rrb#1]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html) ⇒ [dot_file_create](https://github.com/hyPiRion/c-rrb/blob/f47efaf78c28f1b0fa3493fb69bb51482bed6c0e/src/rrb.c#L1484)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [label_pointer](https://github.com/hyPiRion/c-rrb/blob/f47efaf78c28f1b0fa3493fb69bb51482bed6c0e/src/rrb.c#L1466)

**Comment by elfring** [comment]
More update candidates:
- [Return values are still ignored](http://cwe.mitre.org/data/definitions/252.html) from a few relevant function calls, aren't they?
- How do you think about to move visualisation functions to other source files? (Would you like to reuse the basic data structure without them eventually?)

**Comment by hypirion** [comment]
Right, I think I have covered all reasonable return values, and moved the debugging functions into another source file.

The data structure is the main part of this library, and although it provides printing functions, I did not intend printing to be used for "industry" usage. It is provided for either debugging the library itself, to check that this library is at fault for some error, or as a way to learn and understand the RRB-tree itself. Consequently, I'll leave the return value checking as is for now.

If anyone needs more sophisticated error checking from the debugging functions, I'll be happy to hear of the use case and provide functionality to do what you intend within the library.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by elfring** [comment]
I find [the recent adjustment questionable](https://github.com/hyPiRion/c-rrb/commit/1d4ce5d437a4c37840417c20a36c00d6b1d39610). I would prefer an interface like the following.

```
int dot_file_create_safely(char const * name, DotFile* file);
```

**Comment by hypirion** [comment]
So most of these issues are related to how the debugging functionality developed slowly over time: I initially used it for repl-like debugging through lldb/gdb, which was incredibly helpful. I want it to stay that way: Usable when I'm going to develop and debug the library further, while conforming to C standards. But that requires some thought and is a separate issue.
