### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [hypirion/c-rrb#2]
I would like to point out that identifiers like "[`_RRB`](https://github.com/hyPiRion/c-rrb/blob/f47efaf78c28f1b0fa3493fb69bb51482bed6c0e/src/rrb.c#L85)" and "[`_TransientRRB`](https://github.com/hyPiRion/c-rrb/blob/2d4960cc00491b4332bd76687cdd53796e422be0/src/rrb_transients.c#L26)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Thanks for your small source code improvement.

**Comment by elfring** [comment]
Would you also like to [rename the identifier "_DotArray"](https://github.com/hyPiRion/c-rrb/blob/1d4ce5d437a4c37840417c20a36c00d6b1d39610/src/rrb_debug.h#L30)?

**Comment by hypirion** [comment]
Fixed through 476c48a861641d59847356c6ae668551aad35693.
