### ISSUE TITLE
small addition to README

### ISSUE THREAD

**Issue by jkhoogland** [hypirion/c-rrb#9]
Hi,
maybe you can put a line for OSX users in the README file 
as to what is required to build:

brew install boehmgc libtool

This was required on Mavericks,

Cheers 
Jiri

**Comment by hypirion** [comment]
Hi there,

Thanks for the information, much appreciated :) Do you think the addition dc2f62651efbb09b2b84ebfe0b7a01f31036ae6b is understandable enough to get OSX users up and running?

**Comment by jkhoogland** [comment]
Looks good to me :)
Regards
Jiri

2014-11-08 16:09 GMT-05:00 hyPiRion notifications@github.com:

**Comment by hypirion** [comment]
Great, thanks for verifying! :)
